--- 
networks: 
  cdb_network: ~
services: 
  dind_cdb: 
    image: "docker:1.10.3-dind"
    networks: 
      - cdb_network
    privileged: true
  jenkins_cdb:
    build: .
    networks:
      - cdb_network
    volumes:
      - data:/var/jenkins_home
    ports: 
      - "8082:8080"
      - "50000:50000"
    privileged: true
version: "2"

volumes:
  data: